package com.sati.model;
// Generated 20 août 2019 15:27:17 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * AnneeScolaire generated by hbm2java
 */
@Entity
@Table(name = "annee_scolaire", catalog = "sgreclam_bd")
public class AnneeScolaire implements java.io.Serializable {

	private int codeAnneeScol;
	private Enseigner enseigner;
	private Integer debutAnneeScol;
	private Integer finAnneeScol;
	private String libelleAnneeScol;
	private Set<NiveauEtudiant> niveauEtudiants = new HashSet<NiveauEtudiant>(0);
	private Set<NiveauEcue> niveauEcues = new HashSet<NiveauEcue>(0);
	private Set<Reclamation> reclamations = new HashSet<Reclamation>(0);

	public AnneeScolaire() {
	}

	public AnneeScolaire(int codeAnneeScol, Enseigner enseigner) {
		this.codeAnneeScol = codeAnneeScol;
		this.enseigner = enseigner;
	}

	public AnneeScolaire(int codeAnneeScol, Enseigner enseigner, Integer debutAnneeScol, Integer finAnneeScol,
			String libelleAnneeScol, Set<NiveauEtudiant> niveauEtudiants, Set<NiveauEcue> niveauEcues,
			Set<Reclamation> reclamations) {
		this.codeAnneeScol = codeAnneeScol;
		this.enseigner = enseigner;
		this.debutAnneeScol = debutAnneeScol;
		this.finAnneeScol = finAnneeScol;
		this.libelleAnneeScol = libelleAnneeScol;
		this.niveauEtudiants = niveauEtudiants;
		this.niveauEcues = niveauEcues;
		this.reclamations = reclamations;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "CODE_ANNEE_SCOL", unique = true, nullable = false)
	public int getCodeAnneeScol() {
		return this.codeAnneeScol;
	}

	public void setCodeAnneeScol(int codeAnneeScol) {
		this.codeAnneeScol = codeAnneeScol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ENSEIGNER", nullable = false)
	public Enseigner getEnseigner() {
		return this.enseigner;
	}

	public void setEnseigner(Enseigner enseigner) {
		this.enseigner = enseigner;
	}

	@Column(name = "DEBUT_ANNEE_SCOL")
	public Integer getDebutAnneeScol() {
		return this.debutAnneeScol;
	}

	public void setDebutAnneeScol(Integer debutAnneeScol) {
		this.debutAnneeScol = debutAnneeScol;
	}

	@Column(name = "FIN_ANNEE_SCOL")
	public Integer getFinAnneeScol() {
		return this.finAnneeScol;
	}

	public void setFinAnneeScol(Integer finAnneeScol) {
		this.finAnneeScol = finAnneeScol;
	}

	@Column(name = "LIBELLE_ANNEE_SCOL", length = 10)
	public String getLibelleAnneeScol() {
		return this.libelleAnneeScol;
	}

	public void setLibelleAnneeScol(String libelleAnneeScol) {
		this.libelleAnneeScol = libelleAnneeScol;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anneeScolaire")
	public Set<NiveauEtudiant> getNiveauEtudiants() {
		return this.niveauEtudiants;
	}

	public void setNiveauEtudiants(Set<NiveauEtudiant> niveauEtudiants) {
		this.niveauEtudiants = niveauEtudiants;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "anneeScolaires")
	public Set<NiveauEcue> getNiveauEcues() {
		return this.niveauEcues;
	}

	public void setNiveauEcues(Set<NiveauEcue> niveauEcues) {
		this.niveauEcues = niveauEcues;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anneeScolaire")
	public Set<Reclamation> getReclamations() {
		return this.reclamations;
	}

	public void setReclamations(Set<Reclamation> reclamations) {
		this.reclamations = reclamations;
	}

}
