package com.sati.model;
// Generated 13 sept. 2019 18:13:52 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * AnneeScolaire generated by hbm2java
 */
@Entity
@Table(name = "annee_scolaire", catalog = "sgreclam_bd")
public class AnneeScolaire implements java.io.Serializable {

	private int codeAnneeScol;
	private Integer debutAnneeScol;
	private Integer finAnneeScol;
	private String libelleAnneeScol;
	private Boolean etatAnnee;
	private Set<NiveauEtudiant> niveauEtudiants = new HashSet<NiveauEtudiant>(0);
	private Set<Reclamation> reclamations = new HashSet<Reclamation>(0);
	private Set<Enseigner> enseigners = new HashSet<Enseigner>(0);
	private Set<NiveauEcue> niveauEcues = new HashSet<NiveauEcue>(0);

	public AnneeScolaire() {
	}

	public AnneeScolaire(int codeAnneeScol) {
		this.codeAnneeScol = codeAnneeScol;
	}

	public AnneeScolaire(int codeAnneeScol, Integer debutAnneeScol, Integer finAnneeScol, String libelleAnneeScol,
			Boolean etatAnnee, Set<NiveauEtudiant> niveauEtudiants, Set<Reclamation> reclamations,
			Set<Enseigner> enseigners, Set<NiveauEcue> niveauEcues) {
		this.codeAnneeScol = codeAnneeScol;
		this.debutAnneeScol = debutAnneeScol;
		this.finAnneeScol = finAnneeScol;
		this.libelleAnneeScol = libelleAnneeScol;
		this.etatAnnee = etatAnnee;
		this.niveauEtudiants = niveauEtudiants;
		this.reclamations = reclamations;
		this.enseigners = enseigners;
		this.niveauEcues = niveauEcues;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "CODE_ANNEE_SCOL", unique = true, nullable = false)
	public int getCodeAnneeScol() {
		return this.codeAnneeScol;
	}

	public void setCodeAnneeScol(int codeAnneeScol) {
		this.codeAnneeScol = codeAnneeScol;
	}

	@Column(name = "DEBUT_ANNEE_SCOL")
	public Integer getDebutAnneeScol() {
		return this.debutAnneeScol;
	}

	public void setDebutAnneeScol(Integer debutAnneeScol) {
		this.debutAnneeScol = debutAnneeScol;
	}

	@Column(name = "FIN_ANNEE_SCOL")
	public Integer getFinAnneeScol() {
		return this.finAnneeScol;
	}

	public void setFinAnneeScol(Integer finAnneeScol) {
		this.finAnneeScol = finAnneeScol;
	}

	@Column(name = "LIBELLE_ANNEE_SCOL", length = 10)
	public String getLibelleAnneeScol() {
		return this.libelleAnneeScol;
	}

	public void setLibelleAnneeScol(String libelleAnneeScol) {
		this.libelleAnneeScol = libelleAnneeScol;
	}

	@Column(name = "ETAT_ANNEE")
	public Boolean getEtatAnnee() {
		return this.etatAnnee;
	}

	public void setEtatAnnee(Boolean etatAnnee) {
		this.etatAnnee = etatAnnee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anneeScolaire")
	public Set<NiveauEtudiant> getNiveauEtudiants() {
		return this.niveauEtudiants;
	}

	public void setNiveauEtudiants(Set<NiveauEtudiant> niveauEtudiants) {
		this.niveauEtudiants = niveauEtudiants;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anneeScolaire")
	public Set<Reclamation> getReclamations() {
		return this.reclamations;
	}

	public void setReclamations(Set<Reclamation> reclamations) {
		this.reclamations = reclamations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anneeScolaire")
	public Set<Enseigner> getEnseigners() {
		return this.enseigners;
	}

	public void setEnseigners(Set<Enseigner> enseigners) {
		this.enseigners = enseigners;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "anneeScolaires")
	public Set<NiveauEcue> getNiveauEcues() {
		return this.niveauEcues;
	}

	public void setNiveauEcues(Set<NiveauEcue> niveauEcues) {
		this.niveauEcues = niveauEcues;
	}

}
