package com.sati.model;
// Generated 20 août 2019 15:27:17 by Hibernate Tools 5.2.8.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Enseigner generated by hbm2java
 */
@Entity
@Table(name = "enseigner", catalog = "sgreclam_bd")
public class Enseigner implements java.io.Serializable {

	private int codeEnseigner;
	private Ecue ecue;
	private Enseignant enseignant;
	private Date dateEnseigner;
	private Set<AnneeScolaire> anneeScolaires = new HashSet<AnneeScolaire>(0);

	public Enseigner() {
	}

	public Enseigner(int codeEnseigner, Ecue ecue, Enseignant enseignant) {
		this.codeEnseigner = codeEnseigner;
		this.ecue = ecue;
		this.enseignant = enseignant;
	}

	public Enseigner(int codeEnseigner, Ecue ecue, Enseignant enseignant, Date dateEnseigner,
			Set<AnneeScolaire> anneeScolaires) {
		this.codeEnseigner = codeEnseigner;
		this.ecue = ecue;
		this.enseignant = enseignant;
		this.dateEnseigner = dateEnseigner;
		this.anneeScolaires = anneeScolaires;
	}

	@Id

	@Column(name = "CODE_ENSEIGNER", unique = true, nullable = false)
	public int getCodeEnseigner() {
		return this.codeEnseigner;
	}

	public void setCodeEnseigner(int codeEnseigner) {
		this.codeEnseigner = codeEnseigner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ECUE", nullable = false)
	public Ecue getEcue() {
		return this.ecue;
	}

	public void setEcue(Ecue ecue) {
		this.ecue = ecue;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MATRICULE_ENSEI", nullable = false)
	public Enseignant getEnseignant() {
		return this.enseignant;
	}

	public void setEnseignant(Enseignant enseignant) {
		this.enseignant = enseignant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_ENSEIGNER", length = 10)
	public Date getDateEnseigner() {
		return this.dateEnseigner;
	}

	public void setDateEnseigner(Date dateEnseigner) {
		this.dateEnseigner = dateEnseigner;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enseigner")
	public Set<AnneeScolaire> getAnneeScolaires() {
		return this.anneeScolaires;
	}

	public void setAnneeScolaires(Set<AnneeScolaire> anneeScolaires) {
		this.anneeScolaires = anneeScolaires;
	}

}
