package com.sati.model;
// Generated 3 sept. 2019 14:31:19 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Enseigner generated by hbm2java
 */
@Entity
@Table(name = "enseigner", catalog = "sgreclam_bd")
public class Enseigner implements java.io.Serializable {

	private int codeEnseigner;
	private AnneeScolaire anneeScolaire;
	private Ecue ecue;
	private Enseignant enseignant;
	private Date dateEnseigner;

	public Enseigner() {
	}

	public Enseigner(int codeEnseigner, AnneeScolaire anneeScolaire, Ecue ecue, Enseignant enseignant) {
		this.codeEnseigner = codeEnseigner;
		this.anneeScolaire = anneeScolaire;
		this.ecue = ecue;
		this.enseignant = enseignant;
	}

	public Enseigner(int codeEnseigner, AnneeScolaire anneeScolaire, Ecue ecue, Enseignant enseignant,
			Date dateEnseigner) {
		this.codeEnseigner = codeEnseigner;
		this.anneeScolaire = anneeScolaire;
		this.ecue = ecue;
		this.enseignant = enseignant;
		this.dateEnseigner = dateEnseigner;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "CODE_ENSEIGNER", unique = true, nullable = false)
	public int getCodeEnseigner() {
		return this.codeEnseigner;
	}

	public void setCodeEnseigner(int codeEnseigner) {
		this.codeEnseigner = codeEnseigner;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ANNEE_SCOL", nullable = false)
	public AnneeScolaire getAnneeScolaire() {
		return this.anneeScolaire;
	}

	public void setAnneeScolaire(AnneeScolaire anneeScolaire) {
		this.anneeScolaire = anneeScolaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ECUE", nullable = false)
	public Ecue getEcue() {
		return this.ecue;
	}

	public void setEcue(Ecue ecue) {
		this.ecue = ecue;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MATRICULE_ENSEI", nullable = false)
	public Enseignant getEnseignant() {
		return this.enseignant;
	}

	public void setEnseignant(Enseignant enseignant) {
		this.enseignant = enseignant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_ENSEIGNER", length = 10)
	public Date getDateEnseigner() {
		return this.dateEnseigner;
	}

	public void setDateEnseigner(Date dateEnseigner) {
		this.dateEnseigner = dateEnseigner;
	}

}
