package com.sati.model;
// Generated 3 sept. 2019 16:00:21 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Etudiant generated by hbm2java
 */
@Entity
@Table(name = "etudiant", catalog = "sgreclam_bd")
public class Etudiant implements java.io.Serializable {

	private String matriculeEtude;
	private Sexe sexe;
	private String nomEtud;
	private String prenomsEtude;
	private Date dateNaissance;
	private Set<NiveauEtudiant> niveauEtudiants = new HashSet<NiveauEtudiant>(0);
	private Set<Reclamation> reclamations = new HashSet<Reclamation>(0);

	public Etudiant() {
	}

	public Etudiant(String matriculeEtude, Sexe sexe) {
		this.matriculeEtude = matriculeEtude;
		this.sexe = sexe;
	}

	public Etudiant(String matriculeEtude, Sexe sexe, String nomEtud, String prenomsEtude, Date dateNaissance,
			Set<NiveauEtudiant> niveauEtudiants, Set<Reclamation> reclamations) {
		this.matriculeEtude = matriculeEtude;
		this.sexe = sexe;
		this.nomEtud = nomEtud;
		this.prenomsEtude = prenomsEtude;
		this.dateNaissance = dateNaissance;
		this.niveauEtudiants = niveauEtudiants;
		this.reclamations = reclamations;
	}

	@Id

	@Column(name = "MATRICULE_ETUDE", unique = true, nullable = false, length = 15)
	public String getMatriculeEtude() {
		return this.matriculeEtude;
	}

	public void setMatriculeEtude(String matriculeEtude) {
		this.matriculeEtude = matriculeEtude;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_SEXE", nullable = false)
	public Sexe getSexe() {
		return this.sexe;
	}

	public void setSexe(Sexe sexe) {
		this.sexe = sexe;
	}

	@Column(name = "NOM_ETUD", length = 25)
	public String getNomEtud() {
		return this.nomEtud;
	}

	public void setNomEtud(String nomEtud) {
		this.nomEtud = nomEtud;
	}

	@Column(name = "PRENOMS_ETUDE", length = 50)
	public String getPrenomsEtude() {
		return this.prenomsEtude;
	}

	public void setPrenomsEtude(String prenomsEtude) {
		this.prenomsEtude = prenomsEtude;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_NAISSANCE", length = 10)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etudiant")
	public Set<NiveauEtudiant> getNiveauEtudiants() {
		return this.niveauEtudiants;
	}

	public void setNiveauEtudiants(Set<NiveauEtudiant> niveauEtudiants) {
		this.niveauEtudiants = niveauEtudiants;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etudiant")
	public Set<Reclamation> getReclamations() {
		return this.reclamations;
	}

	public void setReclamations(Set<Reclamation> reclamations) {
		this.reclamations = reclamations;
	}

}
