package com.sati.model;
// Generated 13 sept. 2019 18:13:52 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * MotifReclamation generated by hbm2java
 */
@Entity
@Table(name = "motif_reclamation", catalog = "sgreclam_bd")
public class MotifReclamation implements java.io.Serializable {

	private int codeMotifReclam;
	private String libelleMotifReclam;
	private Set<Reclamation> reclamations = new HashSet<Reclamation>(0);

	public MotifReclamation() {
	}

	public MotifReclamation(int codeMotifReclam) {
		this.codeMotifReclam = codeMotifReclam;
	}

	public MotifReclamation(int codeMotifReclam, String libelleMotifReclam, Set<Reclamation> reclamations) {
		this.codeMotifReclam = codeMotifReclam;
		this.libelleMotifReclam = libelleMotifReclam;
		this.reclamations = reclamations;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "CODE_MOTIF_RECLAM", unique = true, nullable = false)
	public int getCodeMotifReclam() {
		return this.codeMotifReclam;
	}

	public void setCodeMotifReclam(int codeMotifReclam) {
		this.codeMotifReclam = codeMotifReclam;
	}

	@Column(name = "LIBELLE_MOTIF_RECLAM", length = 15)
	public String getLibelleMotifReclam() {
		return this.libelleMotifReclam;
	}

	public void setLibelleMotifReclam(String libelleMotifReclam) {
		this.libelleMotifReclam = libelleMotifReclam;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "motifReclamation")
	public Set<Reclamation> getReclamations() {
		return this.reclamations;
	}

	public void setReclamations(Set<Reclamation> reclamations) {
		this.reclamations = reclamations;
	}

}
