package com.sati.model;
// Generated 19 oct. 2019 09:43:29 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * NiveauEcue generated by hbm2java
 */
@Entity
@Table(name = "niveau_ecue", catalog = "sgreclam_bd")
public class NiveauEcue implements java.io.Serializable {

	private int codeNiveauEcue;
	private AnneeScolaire anneeScolaire;
	private Ecue ecue;
	private Niveau niveau;
	private String libeleNiveauEcue;

	public NiveauEcue() {
	}

	public NiveauEcue(int codeNiveauEcue, AnneeScolaire anneeScolaire, Ecue ecue, Niveau niveau) {
		this.codeNiveauEcue = codeNiveauEcue;
		this.anneeScolaire = anneeScolaire;
		this.ecue = ecue;
		this.niveau = niveau;
	}

	public NiveauEcue(int codeNiveauEcue, AnneeScolaire anneeScolaire, Ecue ecue, Niveau niveau,
			String libeleNiveauEcue) {
		this.codeNiveauEcue = codeNiveauEcue;
		this.anneeScolaire = anneeScolaire;
		this.ecue = ecue;
		this.niveau = niveau;
		this.libeleNiveauEcue = libeleNiveauEcue;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "CODE_NIVEAU_ECUE", unique = true, nullable = false)
	public int getCodeNiveauEcue() {
		return this.codeNiveauEcue;
	}

	public void setCodeNiveauEcue(int codeNiveauEcue) {
		this.codeNiveauEcue = codeNiveauEcue;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ANNEE_SCOL", nullable = false)
	public AnneeScolaire getAnneeScolaire() {
		return this.anneeScolaire;
	}

	public void setAnneeScolaire(AnneeScolaire anneeScolaire) {
		this.anneeScolaire = anneeScolaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ECUE", nullable = false)
	public Ecue getEcue() {
		return this.ecue;
	}

	public void setEcue(Ecue ecue) {
		this.ecue = ecue;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_NIVEAU", nullable = false)
	public Niveau getNiveau() {
		return this.niveau;
	}

	public void setNiveau(Niveau niveau) {
		this.niveau = niveau;
	}

	@Column(name = "LIBELE_NIVEAU_ECUE", length = 15)
	public String getLibeleNiveauEcue() {
		return this.libeleNiveauEcue;
	}

	public void setLibeleNiveauEcue(String libeleNiveauEcue) {
		this.libeleNiveauEcue = libeleNiveauEcue;
	}

}
