package com.sati.model;
// Generated 3 sept. 2019 16:00:21 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * NiveauEcue generated by hbm2java
 */
@Entity
@Table(name = "niveau_ecue", catalog = "sgreclam_bd")
public class NiveauEcue implements java.io.Serializable {

	private int codeNiveauEcue;
	private Ecue ecue;
	private Niveau niveau;
	private String libeleNiveauEcue;
	private Set<AnneeScolaire> anneeScolaires = new HashSet<AnneeScolaire>(0);

	public NiveauEcue() {
	}

	public NiveauEcue(int codeNiveauEcue, Ecue ecue, Niveau niveau) {
		this.codeNiveauEcue = codeNiveauEcue;
		this.ecue = ecue;
		this.niveau = niveau;
	}

	public NiveauEcue(int codeNiveauEcue, Ecue ecue, Niveau niveau, String libeleNiveauEcue,
			Set<AnneeScolaire> anneeScolaires) {
		this.codeNiveauEcue = codeNiveauEcue;
		this.ecue = ecue;
		this.niveau = niveau;
		this.libeleNiveauEcue = libeleNiveauEcue;
		this.anneeScolaires = anneeScolaires;
	}

	@Id

	@Column(name = "CODE_NIVEAU_ECUE", unique = true, nullable = false)
	public int getCodeNiveauEcue() {
		return this.codeNiveauEcue;
	}

	public void setCodeNiveauEcue(int codeNiveauEcue) {
		this.codeNiveauEcue = codeNiveauEcue;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ECUE", nullable = false)
	public Ecue getEcue() {
		return this.ecue;
	}

	public void setEcue(Ecue ecue) {
		this.ecue = ecue;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_NIVEAU", nullable = false)
	public Niveau getNiveau() {
		return this.niveau;
	}

	public void setNiveau(Niveau niveau) {
		this.niveau = niveau;
	}

	@Column(name = "LIBELE_NIVEAU_ECUE", length = 15)
	public String getLibeleNiveauEcue() {
		return this.libeleNiveauEcue;
	}

	public void setLibeleNiveauEcue(String libeleNiveauEcue) {
		this.libeleNiveauEcue = libeleNiveauEcue;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "association_19", catalog = "sgreclam_bd", joinColumns = {
			@JoinColumn(name = "CODE_NIVEAU_ECUE", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "CODE_ANNEE_SCOL", nullable = false, updatable = false) })
	public Set<AnneeScolaire> getAnneeScolaires() {
		return this.anneeScolaires;
	}

	public void setAnneeScolaires(Set<AnneeScolaire> anneeScolaires) {
		this.anneeScolaires = anneeScolaires;
	}

}
