package com.sati.model;
// Generated 9 sept. 2019 14:39:29 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * NiveauEtudiant generated by hbm2java
 */
@Entity
@Table(name = "niveau_etudiant", catalog = "sgreclam_bd")
public class NiveauEtudiant implements java.io.Serializable {

	private int codeNiveauEtud;
	private AnneeScolaire anneeScolaire;
	private Etudiant etudiant;
	private Niveau niveau;
	private Date dateNiveauEtud;

	public NiveauEtudiant() {
	}

	public NiveauEtudiant(int codeNiveauEtud, AnneeScolaire anneeScolaire, Etudiant etudiant, Niveau niveau) {
		this.codeNiveauEtud = codeNiveauEtud;
		this.anneeScolaire = anneeScolaire;
		this.etudiant = etudiant;
		this.niveau = niveau;
	}

	public NiveauEtudiant(int codeNiveauEtud, AnneeScolaire anneeScolaire, Etudiant etudiant, Niveau niveau,
			Date dateNiveauEtud) {
		this.codeNiveauEtud = codeNiveauEtud;
		this.anneeScolaire = anneeScolaire;
		this.etudiant = etudiant;
		this.niveau = niveau;
		this.dateNiveauEtud = dateNiveauEtud;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "CODE_NIVEAU_ETUD", unique = true, nullable = false)
	public int getCodeNiveauEtud() {
		return this.codeNiveauEtud;
	}

	public void setCodeNiveauEtud(int codeNiveauEtud) {
		this.codeNiveauEtud = codeNiveauEtud;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_ANNEE_SCOL", nullable = false)
	public AnneeScolaire getAnneeScolaire() {
		return this.anneeScolaire;
	}

	public void setAnneeScolaire(AnneeScolaire anneeScolaire) {
		this.anneeScolaire = anneeScolaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "MATRICULE_ETUDE", nullable = false)
	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_NIVEAU", nullable = false)
	public Niveau getNiveau() {
		return this.niveau;
	}

	public void setNiveau(Niveau niveau) {
		this.niveau = niveau;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_NIVEAU_ETUD", length = 10)
	public Date getDateNiveauEtud() {
		return this.dateNiveauEtud;
	}

	public void setDateNiveauEtud(Date dateNiveauEtud) {
		this.dateNiveauEtud = dateNiveauEtud;
	}

}
