package com.sati.model;
// Generated 19 oct. 2019 09:43:29 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Reclamation generated by hbm2java
 */
@Entity
@Table(name = "reclamation", catalog = "sgreclam_bd")
public class Reclamation implements java.io.Serializable {

	private int numeroReclam;
	private EtatReclamation etatReclamation;
	private Etudiant etudiant;
	private Evaluation evaluation;
	private MotifReclamation motifReclamation;
	private RetourReclamation retourReclamation;
	private Date dateReclam;
	private Date dateRetourReclam;
	private Date dateEtatReclam;
	private String detailReclam;
	private String fichierReclam;

	public Reclamation() {
	}

	public Reclamation(int numeroReclam, Etudiant etudiant, Evaluation evaluation, MotifReclamation motifReclamation) {
		this.numeroReclam = numeroReclam;
		this.etudiant = etudiant;
		this.evaluation = evaluation;
		this.motifReclamation = motifReclamation;
	}

	public Reclamation(int numeroReclam, EtatReclamation etatReclamation, Etudiant etudiant, Evaluation evaluation,
			MotifReclamation motifReclamation, RetourReclamation retourReclamation, Date dateReclam,
			Date dateRetourReclam, Date dateEtatReclam, String detailReclam, String fichierReclam) {
		this.numeroReclam = numeroReclam;
		this.etatReclamation = etatReclamation;
		this.etudiant = etudiant;
		this.evaluation = evaluation;
		this.motifReclamation = motifReclamation;
		this.retourReclamation = retourReclamation;
		this.dateReclam = dateReclam;
		this.dateRetourReclam = dateRetourReclam;
		this.dateEtatReclam = dateEtatReclam;
		this.detailReclam = detailReclam;
		this.fichierReclam = fichierReclam;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "NUMERO_RECLAM", unique = true, nullable = false)
	public int getNumeroReclam() {
		return this.numeroReclam;
	}

	public void setNumeroReclam(int numeroReclam) {
		this.numeroReclam = numeroReclam;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_ETAT_RECLAM")
	public EtatReclamation getEtatReclamation() {
		return this.etatReclamation;
	}

	public void setEtatReclamation(EtatReclamation etatReclamation) {
		this.etatReclamation = etatReclamation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "MATRICULE_ETUDE", nullable = false)
	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_EVALUATION", nullable = false)
	public Evaluation getEvaluation() {
		return this.evaluation;
	}

	public void setEvaluation(Evaluation evaluation) {
		this.evaluation = evaluation;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "CODE_MOTIF_RECLAM", nullable = false)
	public MotifReclamation getMotifReclamation() {
		return this.motifReclamation;
	}

	public void setMotifReclamation(MotifReclamation motifReclamation) {
		this.motifReclamation = motifReclamation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CODE_RETOUR_RECLAM")
	public RetourReclamation getRetourReclamation() {
		return this.retourReclamation;
	}

	public void setRetourReclamation(RetourReclamation retourReclamation) {
		this.retourReclamation = retourReclamation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_RECLAM", length = 19)
	public Date getDateReclam() {
		return this.dateReclam;
	}

	public void setDateReclam(Date dateReclam) {
		this.dateReclam = dateReclam;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_RETOUR_RECLAM", length = 19)
	public Date getDateRetourReclam() {
		return this.dateRetourReclam;
	}

	public void setDateRetourReclam(Date dateRetourReclam) {
		this.dateRetourReclam = dateRetourReclam;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DATE_ETAT_RECLAM", length = 19)
	public Date getDateEtatReclam() {
		return this.dateEtatReclam;
	}

	public void setDateEtatReclam(Date dateEtatReclam) {
		this.dateEtatReclam = dateEtatReclam;
	}

	@Column(name = "DETAIL_RECLAM", length = 65535)
	public String getDetailReclam() {
		return this.detailReclam;
	}

	public void setDetailReclam(String detailReclam) {
		this.detailReclam = detailReclam;
	}

	@Column(name = "FICHIER_RECLAM", length = 50)
	public String getFichierReclam() {
		return this.fichierReclam;
	}

	public void setFichierReclam(String fichierReclam) {
		this.fichierReclam = fichierReclam;
	}

}
