package com.sati.model;
// Generated 9 sept. 2019 14:39:29 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Sexe generated by hbm2java
 */
@Entity
@Table(name = "sexe", catalog = "sgreclam_bd")
public class Sexe implements java.io.Serializable {

	private int codeSexe;
	private String libelleSexe;
	private Set<Enseignant> enseignants = new HashSet<Enseignant>(0);
	private Set<Etudiant> etudiants = new HashSet<Etudiant>(0);

	public Sexe() {
	}

	public Sexe(int codeSexe) {
		this.codeSexe = codeSexe;
	}

	public Sexe(int codeSexe, String libelleSexe, Set<Enseignant> enseignants, Set<Etudiant> etudiants) {
		this.codeSexe = codeSexe;
		this.libelleSexe = libelleSexe;
		this.enseignants = enseignants;
		this.etudiants = etudiants;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "CODE_SEXE", unique = true, nullable = false)
	public int getCodeSexe() {
		return this.codeSexe;
	}

	public void setCodeSexe(int codeSexe) {
		this.codeSexe = codeSexe;
	}

	@Column(name = "LIBELLE_SEXE", length = 15)
	public String getLibelleSexe() {
		return this.libelleSexe;
	}

	public void setLibelleSexe(String libelleSexe) {
		this.libelleSexe = libelleSexe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sexe")
	public Set<Enseignant> getEnseignants() {
		return this.enseignants;
	}

	public void setEnseignants(Set<Enseignant> enseignants) {
		this.enseignants = enseignants;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sexe")
	public Set<Etudiant> getEtudiants() {
		return this.etudiants;
	}

	public void setEtudiants(Set<Etudiant> etudiants) {
		this.etudiants = etudiants;
	}

}
