package com.sati.model;
// Generated 3 sept. 2019 16:00:21 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TypeEvaluation generated by hbm2java
 */
@Entity
@Table(name = "type_evaluation", catalog = "sgreclam_bd")
public class TypeEvaluation implements java.io.Serializable {

	private int codeTypeEvalu;
	private String libelleTypeEvalu;
	private Set<Evaluation> evaluations = new HashSet<Evaluation>(0);

	public TypeEvaluation() {
	}

	public TypeEvaluation(int codeTypeEvalu) {
		this.codeTypeEvalu = codeTypeEvalu;
	}

	public TypeEvaluation(int codeTypeEvalu, String libelleTypeEvalu, Set<Evaluation> evaluations) {
		this.codeTypeEvalu = codeTypeEvalu;
		this.libelleTypeEvalu = libelleTypeEvalu;
		this.evaluations = evaluations;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "CODE_TYPE_EVALU", unique = true, nullable = false)
	public int getCodeTypeEvalu() {
		return this.codeTypeEvalu;
	}

	public void setCodeTypeEvalu(int codeTypeEvalu) {
		this.codeTypeEvalu = codeTypeEvalu;
	}

	@Column(name = "LIBELLE_TYPE_EVALU", length = 10)
	public String getLibelleTypeEvalu() {
		return this.libelleTypeEvalu;
	}

	public void setLibelleTypeEvalu(String libelleTypeEvalu) {
		this.libelleTypeEvalu = libelleTypeEvalu;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeEvaluation")
	public Set<Evaluation> getEvaluations() {
		return this.evaluations;
	}

	public void setEvaluations(Set<Evaluation> evaluations) {
		this.evaluations = evaluations;
	}

}
