package com.sati.model;
// Generated 13 sept. 2019 18:13:52 by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * TypeActeur generated by hbm2java
 */
@Entity
@Table(name = "type_acteur", catalog = "sgreclam_bd")
public class TypeActeur implements java.io.Serializable {

	private int codeType;
	private String libelleTypeAct;
	private Set<UserAuthentication> userAuthentications = new HashSet<UserAuthentication>(0);

	public TypeActeur() {
	}

	public TypeActeur(int codeType) {
		this.codeType = codeType;
	}

	public TypeActeur(int codeType, String libelleTypeAct, Set<UserAuthentication> userAuthentications) {
		this.codeType = codeType;
		this.libelleTypeAct = libelleTypeAct;
		this.userAuthentications = userAuthentications;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "CODE_TYPE", unique = true, nullable = false)
	public int getCodeType() {
		return this.codeType;
	}

	public void setCodeType(int codeType) {
		this.codeType = codeType;
	}

	@Column(name = "LIBELLE_TYPE_ACT", length = 25)
	public String getLibelleTypeAct() {
		return this.libelleTypeAct;
	}

	public void setLibelleTypeAct(String libelleTypeAct) {
		this.libelleTypeAct = libelleTypeAct;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeActeur")
	public Set<UserAuthentication> getUserAuthentications() {
		return this.userAuthentications;
	}

	public void setUserAuthentications(Set<UserAuthentication> userAuthentications) {
		this.userAuthentications = userAuthentications;
	}

}
