package com.sati.model;
// Generated 20 août 2019 15:27:17 by Hibernate Tools 5.2.8.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Ue generated by hbm2java
 */
@Entity
@Table(name = "ue", catalog = "sgreclam_bd")
public class Ue implements java.io.Serializable {

	private int codeUe;
	private String libeleUe;
	private Set<Ecue> ecues = new HashSet<Ecue>(0);

	public Ue() {
	}

	public Ue(int codeUe) {
		this.codeUe = codeUe;
	}

	public Ue(int codeUe, String libeleUe, Set<Ecue> ecues) {
		this.codeUe = codeUe;
		this.libeleUe = libeleUe;
		this.ecues = ecues;
	}

	@Id
	@GenericGenerator(name="lekerand" , strategy="increment")
	@GeneratedValue(generator="lekerand")
	@Column(name = "CODE_UE", unique = true, nullable = false)
	public int getCodeUe() {
		return this.codeUe;
	}

	public void setCodeUe(int codeUe) {
		this.codeUe = codeUe;
	}

	@Column(name = "LIBELE_UE", length = 20)
	public String getLibeleUe() {
		return this.libeleUe;
	}

	public void setLibeleUe(String libeleUe) {
		this.libeleUe = libeleUe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ue")
	public Set<Ecue> getEcues() {
		return this.ecues;
	}

	public void setEcues(Set<Ecue> ecues) {
		this.ecues = ecues;
	}

}
